//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons_by_subject
    {
        public int Id { get; set; }
        public int SubjectId { get; set; }
        public int NubmerOfLessons { get; set; }
    
        public virtual Subjects Subjects { get; set; }
    }
}
