//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public int TeacherId { get; set; }
        public int UserId { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
